---

- name: "download and install Rust"
  include_tasks: "rust_download_install.yml"
- name: "add to shell completion and eviroment"
  include_tasks: "rust_env.yml"
- name: "install applications"
  include_tasks: "rust_apps.yml"

- name: "rustup update"
  shell: rustup update
