---

- name: "download rustup-init.sh from https://www.rustup.rs"
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init.sh
    mode: 0755

- block:

  - name: "install Rust with /tmp/rustup-init.sh, run by {{ ansible_user_id }}"
    shell: '/tmp/rustup-init.sh -y' 

  - name: "check if creat installed"
    stat: path=~/.cargo/bin/{{ item }}
    with_items: "{{ rust.crates }}"
    register: rust_crate

  - name: "install common package"
    shell: ~/.cargo/bin/rustup run stable cargo install {{ item.item }}
    with_items: "{{ rust_crate.results }}"
    when:
      - item.stat.exists == False 

  # - name: install rust targets
  #   shell: ~/.cargo/bin/rustup target add {{ item }}
  #   with_items: "{{ rust.targets }}"

  become: yes
  become_user: "{{ ansible_user_id }}"
