---
# File     : rust_download_install.yml
# Created  : <2018-1-21 Sun 01:53:48 GMT>
# Modified : <2018-1-21 Sun 01:54:48 GMT> Sharlatan

- name: "download rustup-init.sh from https://www.rustup.rs"
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init.sh
    mode: 0755

- block:
  - name: "install Rust with /tmp/rustup-init.sh"
    shell: '/tmp/rustup-init.sh -y' 

  - name: "components"
    shell: " ~/.cargo/bin/rustup component add {{ item }}"
    with_items: "{{ rust.components }}"

  - name: "check if crate installed"
    shell: ~/.cargo/bin/cargo install --list
    register: cargo_pkgs

  - debug:
      msg: "{{ 'exa' in cargo_pkgs.stdout  }}"

  - name: "common crates"
    shell: ~/.cargo/bin/rustup run stable cargo install {{ item }}
    when: item not in cargo_pkgs.stdout
    with_items: "{{ rust.crates }}"

  - name: install rust targets
    shell: ~/.cargo/bin/rustup target add {{ item }}
    with_items: "{{ rust.targets }}"

  - name: "rustup update"
    shell: rustup update

  become: yes
  become_user: "{{ ansible_user_id }}"
...
# End of rust_download_install.yml
