---
- name: "bash directory"
  file:
    path: /etc/bash_completion.d
    state: directory
    recurse: yes

- name: "bash completion"
  shell: ~/.cargo/bin/rustup completions bash > /etc/bash_completion.d/rustup.bash-completion
  args:
    creates: /etc/bash_completion.d/rustup.bash-completion

- block:
    - name: "fish directory"
      file:
        path: ~/.config/fish/completions
        state: directory
        recurse: yes
    - name: "fish complitions"
      shell: ~/.cargo/bin/rustup completions fish > ~/.config/fish/completions/rustup.fish
      args:
        creates: ~/.config/fish/completions/rustup.fish
    - name: "zsh directory"
      file:
        path: ~/.zfunc/completions
        state: directory
        recurse: yes
    - name: "zsh complitions"
      shell: ~/.cargo/bin/rustup completions zsh > ~/.zfunc/completions/_rustup
      args:
        creates: ~/.zfunc/completions/_rustup

    - name: "get rust sysroot"
      shell: ~/.cargo/bin/rustc --print sysroot
      register: rust_sysroot

    - name: "add ~/.cargo/bin to ~/.bashrc"
      lineinfile:
        path: ~/.bashrc
        regexp: "^.*export.*cargo/.*$"
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'

    - name: "export RUST_SRC_PATH to ~/.bashrc"
      lineinfile:
        path: ~/.bashrc
        regexp: "^.*export.*RUST_SRC_PATH/.*$"
        line: 'export RUST_SRC_PATH={{ rust_sysroot.stdout }}/lib/rustlib/src/rust/src'

  become: yes
  become_user: "{{ ansible_user_id }}"
