#!/usr/bin/ansible-playbook
---
# File     : iwi.yml
# Created  : <2017-12-30 Sat 01:16:52 GMT>
# Modified : <2019-7-27 Sat 09:36:48 BST> Sharlatan

- hosts: self
  gather_facts: False

  # roles:
  #   - prelude
  #   #- iwi-sys-upgrade-install
  #   - iwi-sys-dotfiles
    #- iwi-virt-vagrant
    #- iwi-lang-python
    #- iwi-lang-go
    #- iwi-lang-latex
    #- iwi-lang-rust
...
# End of iwi.yml
