#!/usr/bin/ansible-playbook
---
# File     : iwi.yml
# Created  : <2017-12-30 Sat 01:16:52 GMT>
# Modified : <2017-12-30 Sat 01:39:38 GMT> Sharlatan

- hosts: self
  gather_facts: False

  roles:
    - prelude
    - iwi-sys-upgrade-install
    - iwi-lang-python
    # - iwi-lang-latex
    # - iwi-lang-rust

# ------------------------------------------------------------------------------
# End of iwi.yml
