#!/usr/bin/ansible-playbook
---
# File     : iwi.yml
# Created  : <2017-12-30 Sat 01:16:52 GMT>
# Modified : <2018-1-30 Tue 22:23:35 GMT> Sharlatan

- hosts: self
  gather_facts: False

  roles:
    - prelude
    - iwi-sys-upgrade-install
    # - iwi-virt-vagrant
    # - iwi-lang-python
    # - iwi-lang-go
    # - iwi-lang-latex
    # - iwi-lang-rust
...
# End of iwi.yml
