---
# File     : install_python.yml
# Created  : <2018-1-05 Fri 22:32:24 GMT>
# Modified : <2018-1-09 Tue 23:22:02 GMT> Sharlatan

# Work around difirent package managers to install requirement depandensy for
# Ansible first.

- name: "apt check"
  raw: command -v apt | grep -q bin && printf APT || printf nil
  register: if_apt
  changed_when: "'APT' in if_apt.stdout"
- name: "apt-get check"
  raw: command -v apt-get | grep -q bin && printf APT_GET || printf nil
  register: if_apt_get
  changed_when: "'APT_GET' in if_apt_get.stdout"
- name: "dnf check"
  raw: command -v dnf | grep -q bin && printf DNF || printf nil
  register: if_dnf
  changed_when: "'DNF' in if_dnf.stdout"
- name: "yum check"
  raw: command -v yum | grep -q bin && printf YUM || printf nil
  register: if_yum
  changed_when: "'YUM' in if_yum.stdout"

- name: "apt install required Python depednancies"
  raw: "apt -y update && apt install -y python-minimal python-setuptools"
  when:
    - "'APT' in if_apt.stdout"

- name: "apt-get install required Python depednancies"
  raw: "apt-get -y update && apt install -y python-minimal python-setuptools"
  when:
    - "'APT_GET' in if_apt_get.stdout"
    - "'nil' in if_apt.stdout"

- name: "dnf install required Python depednancies"
  raw: "dnf install -qy python2 python-simplejson"
  when:
    - "'DNF' in if_dnf.stdout"

- name: "yum install required Python depednancies"
  raw: "yum install -qy python2 python-simplejson"
  when:
    - "'YUM' in if_yum.stdout"
    - "'nil' in if_dnf.stdout"

- name: "control python check"
  raw: command -v python | grep -q bin && echo -n PYTHON || echo -n nil
  register: if_python
  changed_when: "'PYTHON' in if_python.stdout"

- meta: end_play
  when: "'nil' in if_python.stdout"
...
# End of install_python.yml
