---
# File     : main.yml
# Created  : <2017-11-26 Sun 21:15:41 GMT>
# Modified : <2018-1-09 Tue 23:22:41 GMT> Sharlatan

# Make sure that we have Python installed before run the rest of the playbook,
# workaround few different package managers. Depends on BASH build-in *command*

- name: "python check"
  raw: command -v python | grep -q bin && printf PYTHON || printf nil
  register: if_python
  changed_when: "'nil' in if_python.stdout"

- name: "try to install Python dependencies"
  include_tasks: "install_python.yml"
  when:
    - "'nil' in if_python.stdout"

- name: "update cache"
  setup:
...
# End of main.yml
