---

- name: "installed packages"
  dnf:
    name: "*"
    state: latest

- name: "repository for Fedora"
  dnf:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "Fedora"
  with_items: "{{ rpm.repo.fedora }}"

- name: "packages"
  dnf: name={{item.value}} state=latest
  with_dict: "{{ rpm.pkg }}"

- name: "libraries"
  dnf: name={{item}} state=latest
  with_items: "{{ rpm.libs }}"

- name: "autoremove"
  dnf:
    autoremove: yes

# http://docs.ansible.com/ansible/latest/dnf_module.html
