---
# File     : fedora_distribution.yml
# Created  : <2018-1-14 Sun 23:35:16 GMT>
# Modified : <2018-1-14 Sun 23:35:28 GMT> Sharlatan

- name: "lates existing packages"
  dnf:
    name: "*"
    state: latest

- name: "repository"
  dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ repo.fedora }}"

- name: "package groups"
  dnf:
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ dnf.fedora.groups }}"

- name: "additional packages"
  dnf:
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ dnf.fedora.pkgs }}"

- name: "autoremove"
  dnf:
    autoremove: yes
...
# End of
# http://docs.ansible.com/ansible/latest/dnf_module.html
