---
# File     : main.yml
# Created  : <2018-1-09 Tue 23:15:10 GMT>
# Modified : <2018-1-09 Tue 23:15:20 GMT> Sharlatan

- name: "Fedora distribution"
  include_tasks: "fedora_distribution.yml"
  when: ansible_distribution == "Fedora"

- name: "Ubuntu distribution"
  include_tasks: "ubuntu_distribution.yml"
  when: ansible_distribution == "Ubuntu"
...
# End of main.yml
