---

- name: "Fedora distribution"
  include_tasks: "fedora_distribution.yml"
  when: ansible_distribution == "Fedora"

- name: "Ubuntu distribution"
  include_tasks: "ubuntu_distribution.yml"
  when: ansible_distribution == "Ubuntu"
